[package]
name = "one"
version = "0.1.0"
authors = ["kiliaosi <'wangkiliaosi@foxmail.com'>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
two = { path = "../two" }
three = { path = "../three" }